### ISSUE TITLE
What I would give for you to update this mod

### ISSUE THREAD

**Issue by davisao11** [IgnizGitHub/LethalAction#1]
I NEED to kill this anoying homeless guy, and I do fear that you mod is the only way I could possibly do it. But OOOooohhh, the travesty, it does not work with the latest update, I swear, if I could I would give you my precious left ball, the one softly located inside my sweet scrotum. A ball for a homeless' life, would you not say that is a fair trade?

**_PLEASE, I NEED THAT MAN DEAD! HE HAS STOLEN ALMOST 20K FROM ME, I SIMPLY CANNOT LET IT BE!_**

**Comment by IgnizGitHub** [comment]
With 20k, they won't be homeless long. Though until developers of the game make it easier (they say modding support is this winter 2023, we will see), it won't be updated. I did attempt to update just for you, but was hit with errors and suffice to say they're a PITA to work on as is.
